import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();
app.use(express.json());
app.get('/api/health',(req,res)=>res.json({ok:true,service:'EDK Bénédiction'}));
app.use(express.static(path.join(__dirname,'../dist')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../dist/index.html')));
const PORT=process.env.PORT||3000;
app.listen(PORT,()=>console.log(`EDK Bénédiction server running on port ${PORT}`));