import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const WA_NUMBER='2250000000000'; // À remplacer par le vrai numéro WhatsApp du salon
const MAP_QUERY='EDK Bénédiction Daloa Côte d’Ivoire';

const services=[
 {name:'Coiffure',icon:'✂',image:'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=900&q=85',models:[['Brushing','3 000 FCFA'],['Coupe femme','5 000 FCFA'],['Mise en beauté','8 000 FCFA']]},
 {name:'Tresses & Nattes',icon:'✦',image:'https://images.unsplash.com/photo-1605497788044-5a32c7078486?auto=format&fit=crop&w=900&q=85',models:[['Nattes simples','2 000 FCFA'],['Cornrows','5 000 FCFA'],['Box braids','15 000 FCFA'],['Nattes africaines','20 000 FCFA']]},
 {name:'Manucure',icon:'♡',image:'https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=900&q=85',models:[['Limage & finition','500 FCFA'],['Classique','2 000 FCFA'],['French','5 000 FCFA'],['Gel','8 000 FCFA']]},
 {name:'Pédicure',icon:'◌',image:'https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=900&q=85',models:[['Finition ongles','1 000 FCFA'],['Soin classique','3 000 FCFA'],['Beauté des pieds','5 000 FCFA'],['Pédicure complète','8 000 FCFA']]},
 {name:'Maquillage',icon:'✿',image:'https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&w=900&q=85',models:[['Maquillage léger','5 000 FCFA'],['Naturel','7 000 FCFA'],['Soirée','10 000 FCFA'],['Cérémonie','15 000 FCFA']]},
 {name:'Soins beauté',icon:'☼',image:'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=900&q=85',models:[['Soin express','500 FCFA'],['Soin visage','5 000 FCFA'],['Détente','10 000 FCFA'],['Beauté complète','20 000 FCFA']]}
];

function App(){
 const [form,setForm]=useState({name:'',phone:'',service:'',date:'',time:'',message:''});
 const [status,setStatus]=useState('');
 const update=e=>setForm({...form,[e.target.name]:e.target.value});
 const booking=e=>{e.preventDefault();const text=`Bonjour EDK Bénédiction, je souhaite prendre rendez-vous.%0A%0A👤 Nom : ${form.name}%0A📞 Téléphone : ${form.phone}%0A💇 Prestation : ${form.service}%0A📅 Date : ${form.date}%0A⏰ Heure : ${form.time}%0A📝 Message : ${form.message||'Aucun'}`;window.open(`https://wa.me/${WA_NUMBER}?text=${text}`,'_blank');};
 const locate=()=>{if(!navigator.geolocation){setStatus('La géolocalisation n’est pas disponible sur cet appareil.');return}setStatus('Localisation en cours…');navigator.geolocation.getCurrentPosition(p=>{const {latitude,longitude}=p.coords;window.open(`https://www.google.com/maps/dir/?api=1&destination=${latitude},${longitude}&travelmode=driving`,'_blank');setStatus('Votre position a été détectée.');},()=>setStatus('Autorisez la localisation pour obtenir l’itinéraire.'))};
 return <>
  <div className="top">✨ Votre beauté, notre signature — Daloa, Côte d’Ivoire</div>
  <header><a className="logo" href="#home"><b>EDK</b><span>BÉNÉDICTION</span></a><nav>{['Accueil','Services','Galerie','À propos','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase().replace('à ','a')}>{x}</a>)}<a className="cta" href="#rendez-vous">Rendez-vous</a></nav></header>
  <main>
   <section className="hero" id="home"><div><p className="eyebrow">SALON DE BEAUTÉ • DALOA</p><h1>Révélez votre <i>beauté</i>.</h1><p>Coiffure, tresses, manucure, pédicure, maquillage et soins beauté dans une ambiance élégante et chaleureuse.</p><div className="actions"><a className="button dark" href="#rendez-vous">Prendre rendez-vous</a><a className="button" href="#services">Découvrir nos services</a></div><div className="badges"><span>✦ Professionnel</span><span>✦ Sur rendez-vous</span><span>✦ Daloa</span></div></div><div className="hero-photo"><div className="tag"><b>EDK</b><span>Votre moment beauté</span></div></div></section>
   <section className="intro"><div><p className="eyebrow">EDK BÉNÉDICTION</p><h2>Un seul endroit pour prendre soin de vous.</h2></div><p>Nous réunissons plusieurs prestations beauté pour vous offrir une expérience complète : une nouvelle coiffure, des ongles soignés, un maquillage impeccable ou simplement un moment pour vous.</p></section>
   <section className="section" id="services"><div className="heading"><p className="eyebrow">NOS PRESTATIONS</p><h2>Modèles & tarifs</h2><p>Découvrez les modèles disponibles et une grille tarifaire de démonstration allant de 500 à 20 000 FCFA. Les montants pourront être ajustés selon les tarifs réels du salon.</p></div><div className="services">{services.map(s=><article className="service-card" key={s.name}><img className="service-image" src={s.image} alt={`${s.name} — EDK Bénédiction`} loading="lazy"/><div className="service-body"><div className="icon">{s.icon}</div><h3>{s.name}</h3><p>Choisissez le modèle qui vous convient :</p><div className="model-list">{s.models.map(([model,price])=><div className="model-row" key={model}><span>{model}</span><strong>{price}</strong></div>)}</div><a className="service-book" href="#rendez-vous" onClick={()=>setForm(f=>({...f,service:s.name}))}>Réserver cette prestation →</a></div></article>)}</div><div className="price-note"><strong>💰 Grille tarifaire</strong><span>Tarifs affichés à titre de proposition. Ils vont de 500 à 20 000 FCFA et pourront être remplacés par les prix officiels du salon.</span></div></section>
   <section className="split"><div className="split-photo"></div><div><p className="eyebrow">POUR VOUS, POUR VOTRE STYLE</p><h2>Votre prochaine transformation commence ici.</h2><p>Besoin d’un conseil sur une prestation ? Écrivez-nous sur WhatsApp. Nous vous répondons pour vous orienter et convenir d’un créneau.</p><a className="button dark" href="#rendez-vous">Réserver maintenant</a></div></section>
   <section className="section" id="galerie"><div className="heading"><p className="eyebrow">INSPIRATION</p><h2>Notre univers beauté</h2></div><div className="gallery">{['photo-1522337360788-8b13dee7a37e','photo-1604654894610-df63bc536371','photo-1516975080664-ed2fc6a32937','photo-1605497788044-5a32c7078486','photo-1610992015732-2449b76344bc'].map((id,i)=><img key={id} src={`https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`} alt="Beauté EDK" className={i===0?'tall':''} loading="lazy"/>)}</div></section>
   <section className="about" id="a-propos"><div><p className="eyebrow">POURQUOI EDK ?</p><h2>Un salon pensé pour vous faire sentir belle.</h2><p>EDK Bénédiction est votre espace beauté à Daloa pour prendre soin de vos cheveux, de vos mains, de vos pieds et de votre style.</p><div className="features"><span><b>01</b>Accueil chaleureux</span><span><b>02</b>Prestations variées</span><span><b>03</b>Réservation simple</span></div></div><div className="about-photo"></div></section>
   <section className="booking section" id="rendez-vous"><div><p className="eyebrow">RÉSERVATION</p><h2>Réservez votre créneau sur WhatsApp.</h2><p>Remplissez le formulaire et WhatsApp ouvrira automatiquement votre message de réservation.</p></div><form onSubmit={booking}><label>Votre nom<input name="name" value={form.name} onChange={update} placeholder="Ex. Marie Kouassi" required/></label><label>Téléphone<input name="phone" value={form.phone} onChange={update} placeholder="Votre numéro" required/></label><label>Prestation<select name="service" value={form.service} onChange={update} required><option value="">Choisir</option>{services.map(s=><option key={s.name}>{s.name}</option>)}</select></label><div className="row"><label>Date<input name="date" type="date" value={form.date} onChange={update} required/></label><label>Heure<input name="time" type="time" value={form.time} onChange={update} required/></label></div><label>Message<textarea name="message" value={form.message} onChange={update} placeholder="Précision sur votre demande…"/></label><button className="button whatsapp">💬 Confirmer via WhatsApp</button></form></section>
   <section className="location section" id="contact"><div><p className="eyebrow">NOUS TROUVER</p><h2>EDK Bénédiction à Daloa</h2><p>Une fois l’adresse exacte confirmée, nous pourrons remplacer la recherche par les coordonnées GPS précises du salon et préparer son ajout sur Google Maps.</p><div className="details"><b>📍 Daloa, Côte d’Ivoire</b><b>📞 WhatsApp : à renseigner</b></div><div className="actions"><button className="button dark" onClick={locate}>📍 Me géolocaliser</button><a className="button" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(MAP_QUERY)}`} target="_blank" rel="noreferrer">Ouvrir Google Maps</a></div>{status&&<p className="status">{status}</p>}</div><div className="map"><div>📍<b> EDK Bénédiction</b><small>Daloa, Côte d’Ivoire</small><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(MAP_QUERY)}`} target="_blank" rel="noreferrer">Voir sur Google Maps →</a></div></div></section>
  </main><footer><div><a className="logo"><b>EDK</b><span>BÉNÉDICTION</span></a><p>Salon de coiffure & beauté à Daloa.</p></div><div><h4>Navigation</h4><a href="#services">Services</a><a href="#galerie">Galerie</a><a href="#rendez-vous">Rendez-vous</a></div><div><h4>Contact</h4><a href="#contact">Daloa, Côte d’Ivoire</a><a href="#rendez-vous">WhatsApp</a></div></footer><div className="copyright">© {new Date().getFullYear()} EDK Bénédiction. Tous droits réservés.</div>
 </>;
}
createRoot(document.getElementById('root')).render(<App/>);