import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const WA_NUMBER='2250757432898';const WA_LINK=`https://wa.me/${WA_NUMBER}`;const MAP_QUERY='EDK Bénédiction Daloa Côte d’Ivoire';const img=id=>id.startsWith('http')?id:`https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;const braidImg=name=>`https://commons.wikimedia.org/wiki/Special:Redirect/file/${encodeURIComponent(name)}`;
const services=[
{name:'Coiffure',icon:'✂',image:img('photo-1522337360788-8b13dee7a37e'),models:[['Brushing','3 000 FCFA','photo-1522337360788-8b13dee7a37e'],['Coupe femme','5 000 FCFA','photo-1560869713-da86a9ec1e2d'],['Mise en beauté','8 000 FCFA','photo-1595476108010-b4d1f102b1b1'],['Chignon cérémonie','12 000 FCFA','photo-1487412720507-e7ab37603c6f']]},
{name:'Tresses & Nattes',icon:'✦',image:braidImg('African girl braids.jpg'),models:[['Nattes simples','2 000 FCFA','African girl braids.jpg'],['Cornrows africaines','5 000 FCFA','Cornrow Hairstyling.jpg'],['Box braids','15 000 FCFA','African damsel.jpg'],['Tresses africaines avec perles','20 000 FCFA','Osogbo Ogun Festival 2026 (Cowrie Crown).jpg']]},
{name:'Manucure',icon:'♡',image:img('photo-1604654894610-df63bc536371'),models:[['Limage & finition','500 FCFA','photo-1604654894610-df63bc536371'],['Manucure classique','2 000 FCFA','photo-1610992015732-2449b76344bc'],['French','5 000 FCFA','photo-1604654894610-df63bc536371'],['Gel','8 000 FCFA','photo-1571290274554-6a2eaa771e5f']]},
{name:'Pédicure',icon:'◌',image:img('photo-1519014816548-bf5fe059798b'),models:[['Finition ongles','1 000 FCFA','photo-1519014816548-bf5fe059798b'],['Soin classique','3 000 FCFA','photo-1588359348347-9bc6cbbb689e'],['Beauté des pieds','5 000 FCFA','photo-1519014816548-bf5fe059798b'],['Pédicure complète','8 000 FCFA','photo-1519014816548-bf5fe059798b']]},
{name:'Maquillage',icon:'✿',image:img('photo-1516975080664-ed2fc6a32937'),models:[['Maquillage léger','5 000 FCFA','photo-1516975080664-ed2fc6a32937'],['Naturel','7 000 FCFA','photo-1487412720507-e7ab37603c6f'],['Soirée','10 000 FCFA','photo-1516975080664-ed2fc6a32937'],['Cérémonie','15 000 FCFA','photo-1526045478516-99145907023c']]},
{name:'Soins beauté',icon:'☼',image:img('photo-1540555700478-4be289fbecef'),models:[['Soin express','500 FCFA','photo-1540555700478-4be289fbecef'],['Soin visage','5 000 FCFA','photo-1570172619644-dfd03ed5d881'],['Détente','10 000 FCFA','photo-1540555700478-4be289fbecef'],['Beauté complète','20 000 FCFA','photo-1515377905703-c4788e51af15']]}
];
function App(){const [status,setStatus]=useState('');const [selected,setSelected]=useState(null);const openWhatsApp=text=>{const encoded=encodeURIComponent(text);const appUrl=`whatsapp://send?phone=${WA_NUMBER}&text=${encoded}`;const webUrl=`${WA_LINK}?text=${encoded}`;let fallbackTimer;const clearFallback=()=>{if(fallbackTimer)clearTimeout(fallbackTimer);document.removeEventListener('visibilitychange',clearFallback)};document.addEventListener('visibilitychange',clearFallback);window.location.href=appUrl;fallbackTimer=setTimeout(()=>{if(document.visibilityState==='visible')window.location.href=webUrl;clearFallback()},1800)};const quickWhatsApp=()=>openWhatsApp('Bonjour EDK Bénédiction, je souhaite prendre rendez-vous. Pouvez-vous me renseigner sur vos disponibilités et vos tarifs ?');const reserve=(service,model,price)=>{openWhatsApp(`Bonjour EDK Bénédiction, je souhaite réserver.\n\n💇 Prestation : ${service}\n✨ Modèle : ${model}\n💰 Prix affiché : ${price} (négociable)\n\nPouvez-vous me confirmer la disponibilité et le tarif final ?`);setSelected(null)};const locate=()=>{if(!navigator.geolocation){setStatus('La géolocalisation n’est pas disponible sur cet appareil.');return}setStatus('Localisation en cours…');navigator.geolocation.getCurrentPosition(p=>{const {latitude,longitude}=p.coords;window.open(`https://www.google.com/maps/dir/?api=1&destination=${latitude},${longitude}&travelmode=driving`,'_blank');setStatus('Votre position a été détectée.')},()=>setStatus('Autorisez la localisation pour obtenir l’itinéraire.'))};return <>
<div className="top">✨ Votre beauté, notre signature — Daloa, Côte d’Ivoire</div><header><a className="logo" href="#home"><b>EDK</b><span>BÉNÉDICTION</span></a><nav>{['Accueil','Services','Galerie','À propos','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase().replace('à ','a')}>{x}</a>)}<button className="cta" onClick={quickWhatsApp}>Rendez-vous</button></nav></header><main>
<section className="hero" id="home"><div><p className="eyebrow">SALON DE BEAUTÉ • DALOA</p><h1>Révélez votre <i>beauté</i>.</h1><p>Coiffure, tresses, manucure, pédicure, maquillage et soins beauté dans une ambiance élégante et chaleureuse.</p><div className="actions"><button className="button dark" onClick={quickWhatsApp}>💬 Prendre rendez-vous</button><a className="button" href="#services">Découvrir nos services</a></div><div className="badges"><span>✦ Professionnel</span><span>✦ Sur rendez-vous</span><span>✦ Daloa</span></div></div><div className="hero-photo"><div className="tag"><b>EDK</b><span>Votre moment beauté</span></div></div></section>
<section className="intro"><div><p className="eyebrow">EDK BÉNÉDICTION</p><h2>Un seul endroit pour prendre soin de vous.</h2></div><p>Nous réunissons plusieurs prestations beauté pour vous offrir une expérience complète.</p></section>
<section className="section" id="services"><div className="heading"><p className="eyebrow">NOS PRESTATIONS</p><h2>Votre catalogue beauté</h2><p>Cliquez sur une prestation pour ouvrir son catalogue.</p></div><div className="services">{services.map(s=><article className="service-card" key={s.name} onClick={()=>setSelected(s)}><img className="service-image" src={s.image} alt={`${s.name} — EDK Bénédiction`} loading="lazy"/><div className="service-body"><div className="icon">{s.icon}</div><h3>{s.name}</h3><p>{s.models.length} modèles disponibles · Cliquez pour voir le catalogue</p><div className="service-preview">{s.models.slice(0,2).map(([model,price])=><div className="model-row" key={model}><span>{model}</span><strong>{price} <small>• Négociable</small></strong></div>)}</div><button className="service-book catalog-button" type="button">Voir tous les modèles →</button></div></article>)}</div><div className="price-note"><strong>💰 Tarifs</strong><span>Les prix affichés sont indicatifs et <b>négociables</b> avec le salon.</span></div></section>
<section className="split"><div className="split-photo"></div><div><p className="eyebrow">POUR VOUS, POUR VOTRE STYLE</p><h2>Votre prochaine transformation commence ici.</h2><p>Besoin d’un conseil ? Écrivez-nous sur WhatsApp.</p><button className="button dark" onClick={quickWhatsApp}>💬 Réserver sur WhatsApp</button></div></section>
<section className="section" id="galerie"><div className="heading"><p className="eyebrow">INSPIRATION</p><h2>Notre univers beauté</h2></div><div className="gallery">{['photo-1522337360788-8b13dee7a37e','photo-1604654894610-df63bc536371','photo-1516975080664-ed2fc6a32937','photo-1605497788044-5a32c7078486','photo-1610992015732-2449b76344bc'].map((id,i)=><img key={id} src={img(id)} alt="Beauté EDK" className={i===0?'tall':''} loading="lazy"/>)}</div></section>
<section className="about" id="a-propos"><div><p className="eyebrow">POURQUOI EDK ?</p><h2>Un salon pensé pour vous faire sentir belle.</h2><p>EDK Bénédiction est votre espace beauté à Daloa.</p><div className="features"><span><b>01</b>Accueil chaleureux</span><span><b>02</b>Prestations variées</span><span><b>03</b>Réservation simple</span></div></div><div className="about-photo"></div></section>
<section className="location section" id="contact"><div><p className="eyebrow">NOUS TROUVER</p><h2>EDK Bénédiction à Daloa</h2><p>Contactez-nous directement sur WhatsApp.</p><div className="details"><b>📍 Daloa, Côte d’Ivoire</b><b>📞 WhatsApp : 07 57 43 28 98</b></div><div className="actions"><button className="button dark" onClick={locate}>📍 Me géolocaliser</button><button className="button" onClick={quickWhatsApp}>💬 Écrire sur WhatsApp</button><a className="button" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(MAP_QUERY)}`} target="_blank" rel="noreferrer">Ouvrir Google Maps</a></div>{status&&<p className="status">{status}</p>}</div><div className="map"><div>📍<b> EDK Bénédiction</b><small>Daloa, Côte d’Ivoire</small><a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(MAP_QUERY)}`} target="_blank" rel="noreferrer">Voir sur Google Maps →</a></div></div></section>
</main><footer><div><a className="logo"><b>EDK</b><span>BÉNÉDICTION</span></a><p>Salon de coiffure & beauté à Daloa.</p></div><div><h4>Navigation</h4><a href="#services">Services</a><a href="#galerie">Galerie</a><button onClick={quickWhatsApp}>Rendez-vous</button></div><div><h4>Contact</h4><a href="#contact">Daloa, Côte d’Ivoire</a><button onClick={quickWhatsApp}>WhatsApp</button></div></footer><div className="copyright">© {new Date().getFullYear()} EDK Bénédiction. Tous droits réservés.</div>
{selected&&<div className="catalog-overlay" onClick={()=>setSelected(null)}><div className="catalog-modal" onClick={e=>e.stopPropagation()}><button className="catalog-close" onClick={()=>setSelected(null)} aria-label="Fermer">×</button><div className="catalog-head"><p className="eyebrow">CATALOGUE EDK</p><h2>{selected.icon} {selected.name}</h2><p>Choisissez votre modèle et réservez directement sur WhatsApp.</p></div><div className="catalog-grid">{selected.models.map(([model,price,photo])=><article className="catalog-item" key={model}><img src={img(photo)} alt={`${model} - ${selected.name}`} loading="lazy"/><div className="catalog-item-body"><div><h3>{model}</h3><strong>{price} <small>• Négociable</small></strong></div><button className="catalog-reserve" onClick={()=>reserve(selected.name,model,price)}>💬 Réserver ce modèle →</button></div></article>)}</div></div></div>}</>}
createRoot(document.getElementById('root')).render(<App/>);
